### PR TITLE
Linux implementation

### PR DESCRIPTION
**Pull request by bruhmoment21**

### CODE REVIEW

**Comment by cristeigabriel** [comment]
note for whomever contributes: there's 2 panorama SOs (opengl/vulkan)

**Comment by cristeigabriel** [comment]
for whomever's interested in fixing the remainder issues (until then i won't be merging this to main branch), they're listed in the second commit

**Comment by bruhmoment21** [comment]
fixed stuff everything should work as in windows build

image

**Comment by cristeigabriel** [comment]
Could someone confirm that the push I made builds fine on Linux?

**Pull request merged**
